name: Release check, build and deploy
on:
 pull_request:
   types: [closed]
   branches:
    - 'main'

jobs:
  build_and_pub:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_NAME }}

    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t $REPO:${GITHUB_REF_NAME} -f Dockerfile --build-arg TOKEN=test .

      - name: Push image to docker.io
        run: docker push $REPO:${GITHUB_REF_NAME}
