name: Release check, build and deploy
on:
 release:
   types: [published]


jobs:
  build_and_pub:
    runs-on: ubuntu-latest

    steps:
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:${GITHUB_REF_NAME} -f Dockerfile --build-arg token=${{ secrets.BOT_API_KEY }} .

      - name: Push image to docker.io
        run: docker push ${{ secrets.DOCKER_REPO }}:${GITHUB_REF_NAME}
        
  deploy:
    needs: [ build_and_pub ]
    runs-on: ubuntu-latest

    steps:
      - name: Set the value
        run: echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Send webhook for deploy
        run: "curl --silent --show-error --fail -X POST ${{ secrets.DEPLOYMENT_SERVER }} -H 'Authorization: ${{ secrets.CI_TOKEN }}' -H 'Content-Type: application/json' -d '{\"owner\": \"${{ secrets.DOCKER_LOGIN }}\", \"repository\": \"${{ secrets.DOCKER_NAME }}\", \"tag\": \"${{ env.tag }}\"}'"